import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/[pages]/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundColor: {
        frio: "#1100ff",
      },
      colors: {
        cielo: "#2E91D4",
        ballena: "#7AB3DD",
        naranja: "#ED5700",
        frita: "#D76645",
        viola: "#F700DB",
        lime: "#10FF90",
        amarillo: "#F8FF6F",
        dorado: "#F5C652",
        offNegro: "#0F1015",
        ligero: "#F9FF90",
        oscuro: "#1F32EE",
        mar: "#0789D2",
        rojo: "#EE3075",
        rosa: "#F5E0E2",
        morado: "#7E68C6",
        brillo: "#FFFF0A",
        offBlack: "#111313",
        turq: "#1239F6",
        azulito: "#B9FFFF",
        salmon: "#FF8080",
        flor: "#FF1493",
        viol: "#C993FF",
        gris: "#D8D8D8",
        verde: "#00FF00",
        costa: "#00CCFF",
        limon: "#A9FDCA",
        crema: "#F3EFE6",
        zana: "#FF8B07",
        ami: "#FFD700",
        prima: "#00FFCC",
        triste: "#F9F7F7",
        rosas: "#FF9AFF",
        sol: "#FFFF6E",
        nubes: "#FFAA00",
        rayas: "#F6FC8D",
        jardin: "#0485FD",
        fresas: "#DF5B70",
        vapor: "#D8D8D8",
        viol2: "#C479FF",
      },
      fontSize: {
        xxxs: "0.4rem",
        xxs: "0.6rem",
      },
      fontFamily: {
        rain: "Internal Rainbows",
        mana: "Manaspace",
        bit: "Bitblox",
        at: "at01",
        leco: "Leco",
        abad: "Abaddon",
        arc: "Arcade Classic",
        vcr: "Vcr",
        con: "Consolas",
        clar: "Clarity",
        lib: "LibertadR",
        super: "Super",
      },
      backgroundImage: {
        esterilla: `url("https://thedial.infura-ipfs.io/ipfs/QmR5EfV2Ck8owQSmstmNbNUzcd4BToJnj3GnukDhP3n5J3")`,
      },
      zIndex: {
        100: "100",
        200: "200",
        300: "300",
      },
      screens: {
        gal: "480px",
        tab: "800px",
        "1xl": "1460px",
      },
    },
  },
  plugins: [],
};
export default config;
